name: build
on:
 push:
 pull_request:
 schedule:
#Every 50 days at midnight 
    - cron:  "0 0 1/600 * *"

jobs:
  compilejobFedora:
    name: hoppet_on_Fedora
    runs-on: ubuntu-latest
    container:
        image: fedora:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install 
      run: |
           yum -y install  gcc gcc-c++ gcc-gfortran make wget which cmake cmake-data cmake-filesystem lhapdf lhapdf-devel
    - name: Compile
      run: |
          cmake -S . -B BUILD -DCMAKE_INSTALL_PREFIX=$(pwd)/../INSTALL -DHOPPET_ENABLE_FPES=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build BUILD -j
          cmake --install BUILD
          ctest --test-dir BUILD -j 2 --output-on-failure


  compilejob:
    name: hoppet_on_Rocky9_Intel_HPCKIT
    runs-on: ubuntu-latest
    container:
        image: intel/oneapi-hpckit:2024.0.1-devel-rockylinux9
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install 
      run: |
           yum -y install epel-release
           yum -y install make wget which cmake cmake-data cmake-filesystem lhapdf lhapdf-devel
    - name: Compile_with_ifx
      run: |
          cmake -S . -B BUILDifx -DCMAKE_Fortran_COMPILER=ifx -DCMAKE_INSTALL_PREFIX=$(pwd)/../INSTALLifx
          cmake --build BUILDifx -j
          cmake --install BUILDifx
          ctest --test-dir BUILDifx -j 2 --output-on-failure
    - name: Compile_with_ifort
      run: |
          cmake -S . -B BUILDifort -DCMAKE_Fortran_COMPILER=ifort -DCMAKE_INSTALL_PREFIX=$(pwd)/../INSTALLifort
          cmake --build BUILDifort -j
          cmake --install BUILDifort
          ctest --test-dir BUILDifort -j 2 --output-on-failure


  compilejobUbuntu_IBM_XL:
    name: hoppet_on_Ubuntu_IBM_XL
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: QEMU
      run: |
           sudo apt update
           sudo  apt install --yes binfmt-support qemu-user-static wget
           wget  https://github.com/Kitware/CMake/releases/download/v3.17.0-rc3/cmake-3.17.0-rc3.tar.gz
           mkdir -p cmake.src
           tar -xf cmake-3.17.0-rc3.tar.gz --strip-components=1 -C cmake.src
    - name: Check_cmake_cache
      uses: actions/cache@v3
      id: cache
      with:
        path: cmake.bin
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Compile_cmake_for_ppc64le
      if: steps.cache.outputs.cache-hit != 'true'
      uses: addnab/docker-run-action@v3
      with:
        image: ibmcom/xlf-ce
        options: -v ${{ github.workspace }}:/work --platform=linux/ppc64le -e LICENSE=accept
        run: |
          uname -a
          cd cmake.src
          ./bootstrap --prefix=$(pwd)/../cmake.bin --parallel=4 -DCMAKE_USE_OPENSSL=OFF
          make -j
          make install
          cd ..
    - name: Compile_with_xlf
      uses: addnab/docker-run-action@v3
      with:
        image: ibmcom/xlf-ce
        options: -v ${{ github.workspace }}:/work --platform=linux/ppc64le -e LICENSE=accept
        run: |
          uname -a
          export PATH=$(pwd)/cmake.bin:$PATH
          cmake -S . -B BUILDxlf -DCMAKE_Fortran_COMPILER=xlf -DCMAKE_INSTALL_PREFIX=$(pwd)/../INSTALLxlf
          cmake --build BUILDxlf -j
          cmake --install BUILDxlf
          ctest --test-dir BUILDxlf -j 2 --output-on-failure

  compilejobOSX:
    runs-on: macos-latest
    name: hoppet_on_OSX
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install 
      run: |
          brew install wget coreutils gcc
          brew tap davidchall/hep
          brew install lhapdf
    - name: Compile
      run: |
          cmake -S . -B BUILD -DCMAKE_INSTALL_PREFIX=$(pwd)/../INSTALL -DCMAKE_Fortran_COMPILER=gfortran-13  -DHOPPET_ENABLE_FPES=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build BUILD -j 2
          cmake --install BUILD
          ctest --test-dir BUILD -j 2 --output-on-failure
